# Generated by Django 5.2.7 on 2025-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_galleryitem_project_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Alumni', 'Alumni')], default='Active', max_length=10),
        ),
    ]
