# Generated by Django 5.2.7 on 2025-10-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_teammember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
