# Generated by Django 5.2.7 on 2025-10-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_teammember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='joinDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
