# Generated by Django 5.2.7 on 2025-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teammember_email_teammember_joindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('alumni', 'Alumni')], default='Active', max_length=10),
        ),
    ]
