# Generated by Django 5.2.7 on 2025-10-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_teammember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('alumni', 'Alumni')], default='Active', max_length=10),
        ),
    ]
