# Generated by Django 5.2.7 on 2025-10-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_teammember_image_alter_teammember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Alumni', 'Alumni')], default='Active', max_length=10),
        ),
    ]
