# Generated by Django 5.2.7 on 2025-10-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_teammember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.AddField(
            model_name='teammember',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
