# Generated by Django 5.2.7 on 2025-10-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_teammember_email_teammember_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='achievements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('founder', 'Founder'), ('executive', 'Executive Leadership'), ('employee', 'Employee'), ('alumni', 'Alumni')], default='employee', max_length=20),
        ),
    ]
