# Generated by Django 5.2.7 on 2025-10-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_teammember_achievements_teammember_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('office', 'Office'), ('events', 'Events'), ('celebration', 'Celebration')], default='office', max_length=20),
        ),
    ]
