# Generated by Django 5.2.7 on 2025-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_galleryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('office', 'Office'), ('events', 'Events'), ('celebration', 'Celebration'), ('others', 'Others')], default='office', max_length=20),
        ),
    ]
