# Generated by Django 5.2.7 on 2025-10-27 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_galleryitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='from-blue-500 to-purple-600', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default='Briefcase', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('fintech', 'Fintech'), ('saas', 'SaaS'), ('edtech', 'Edtech'), ('ai', 'AI'), ('blockchain', 'Blockchain'), ('devops', 'DevOps'), ('ecommerce', 'Ecommerce'), ('govtech', 'Govtech'), ('enterprise', 'Enterprise')], default='mobile', max_length=100),
        ),
    ]
