# Generated by Django 5.2.7 on 2025-10-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_project_options_project_challenges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='short_description',
            new_name='shortDescription',
        ),
    ]
