# Generated by Django 5.2.7 on 2025-10-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_short_description_project_shortdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='live_url',
            new_name='liveUrl',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='video_url',
            new_name='videoUrl',
        ),
    ]
