# Generated by Django 5.2.7 on 2025-11-24 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_live_url_project_liveurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('iconText', models.CharField(blank=True, max_length=3)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='products/covers/')),
                ('description', models.TextField(blank=True)),
                ('fullDescription', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('education', 'Education'), ('business', 'Business'), ('productivity', 'Productivity'), ('analytics', 'Analytics'), ('communication', 'Communication'), ('development', 'Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('healthcare', 'Healthcare')], default='education', max_length=50)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('In Development', 'In Development'), ('Coming Soon', 'Coming Soon')], default='In Development', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('integrations', models.JSONField(blank=True, default=list)),
                ('support', models.JSONField(blank=True, default=list)),
                ('liveUrl', models.URLField(blank=True)),
                ('demoUrl', models.URLField(blank=True)),
                ('documentationUrl', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('sortOrder', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sortOrder', '-created_at'],
            },
        ),
    ]
