# Generated by Django 5.2.7 on 2025-11-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery',
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='account.product')),
            ],
            options={
                'verbose_name_plural': 'Product Galleries',
            },
        ),
    ]
