# Generated by Django 3.2.7 on 2025-12-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_product_gallery_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='iconText',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
