# Generated by Django 3.2.7 on 2025-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_product_icontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
