# Generated by Django 6.0 on 2025-12-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='team_info',
            field=models.TextField(blank=True),
        ),
    ]
