# Generated by Django 6.0 on 2025-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_product_team_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('fintech', 'Fintech'), ('saas', 'SaaS'), ('edtech', 'Edtech'), ('ai', 'AI'), ('blockchain', 'Blockchain'), ('devops', 'DevOps'), ('ecommerce', 'Ecommerce'), ('govtech', 'Govtech'), ('enterprise', 'Enterprise')], max_length=100),
        ),
    ]
