# Generated by Django 6.0 on 2025-12-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_project_bullets_project_external_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='external_image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
