import os, sys, django
sys.path.append(os.getcwd())
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
django.setup()
from account.models import Project

FINAL_BATCH = [
    {"title": "Abriella Paintings", "slug": "abriella-paintings", "category": "ecommerce", "status": "completed", "shortDescription": "Art gallery e-commerce platform", "description": "Full-featured online art gallery with artist profiles, virtual exhibitions, secure payments, and global shipping integration.", "client": "Art Gallery", "team": "3 developers", "timeline": "7 months", "technologies": ["React", "Node.js", "MongoDB", "Stripe", "Cloudinary",  "AWS S3"], "bullets": ["Artist portfolio management", "Virtual gallery tours", "Secure payment processing", "Shipping calculator", "Art authentication via blockchain", "Auction bidding system"], "challenges": ["High-quality image delivery", "Secure payment processing", "International shipping logistics", "Artwork authentication"], "outcomes": ["500+ artworks listed", "$200K+ sales", "50+ artists onboarded", "International shipping to 30+ countries"], "stats": [{"label": "Artworks", "value": "500+"}, {"label": "Sales", "value": "$200K+"}, {"label": "Artists", "value": "50+"}], "external_image_url": "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800", "is_active": True},
    
    {"title": "Sushrusa E-Clinic - Rural Healthcare Revolution", "slug": "sushrusa-e-clinic", "category": "enterprise", "status": "completed", "shortDescription": "Telemedicine bridges rural India with superspeciality care", "description": "Telemedicine platform connecting rural patients with specialist doctors. Features video consultations, e-prescriptions, medicine delivery, and health records.", "client": "Healthcare NGO", "team": "2 Developers", "timeline": "4 months", "technologies": ["React", "TypeScript", "Vite", "WebRTC", "Node.js", "PostgreSQL", "Twilio", "AWS", "Docker"], "bullets": ["HD video consultations", "E-prescription generation", "Medicine delivery integration", "Electronic health records", "Multi-language support", "Offline diagnosis support"], "challenges": ["Low bandwidth video quality", "Doctor availability scheduling", "Medicine delivery in remote areas", "Patient data privacy"], "outcomes": ["10K+ consultations completed", "Serving 100+ villages", "80% patient satisfaction", "30% reduction in patient travel"], "stats": [{"label": "Consultations", "value": "10K+"}, {"label": "Villages", "value": "100+"}, {"label": "Satisfaction", "value": "80%"}], "external_image_url": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800", "is_active": True},
    
    {"title": "Rafinity AI Healthcare Agent", "slug": "rafinity-ai-healthcare", "category": "ai", "status": "completed", "shortDescription": "Secure healthcare platform with patient/doctor portals", "description": "AI-powered healthcare management platform with separate patient and doctor portals. Features appointment scheduling, medical records, AI symptom checker, and telemedicine.", "client": "Private Healthcare Provider", "team": "1 full-stack developer", "timeline": "1 Month", "technologies": ["Next.js", "TypeScript", "React", "OpenAI API", "PostgreSQL", "Prisma"], "bullets": ["AI symptom analysis", "Appointment management", "Secure medical records", "Doctor-patient messaging", "Prescription management", "Health analytics dashboard"], "challenges": ["HIPAA compliance", "AI accuracy for symptoms", "Real-time availability sync", "Data encryption at rest"], "outcomes": ["500+ patients registered", "95% AI diagnosis accuracy", "200+ appointments monthly", "Zero data breaches"], "stats": [{"label": "Patients", "value": "500+"}, {"label": "AI Accuracy", "value": "95%"}, {"label": "Appointments", "value": "200/mo"}], "external_image_url": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800", "is_active": True},
    
    {"title": "ISKCON Baranga-Patia Digital Platform", "slug": "iskcon-digital-platform", "category": "enterprise", "status": "completed", "shortDescription": "End-to-end Next.js platform for programs, community engagement, donations, and events", "description": "Complete digital platform for ISKCON temple managing programs, events, donations, volunteer coordination, and community engagement.", "client": "ISKCON Temple", "team": "1 Full-stack engineer", "timeline": "1 month", "technologies": ["Next.js", "React", "TypeScript", "Tailwind CSS", "Razorpay", "MongoDB", "Vercel"], "bullets": ["Event and program management", "Online donation platform", "Volunteer coordination", "Live streaming integration", "E-commerce for prasadam", "Community forum"], "challenges": ["High traffic during festivals", "Secure donation processing", "Multi-language content", "Mobile-first design"], "outcomes": ["50K+ monthly visitors", "Rs 10L+ donations collected", "500+ volunteers registered", "100+ events managed annually"], "stats": [{"label": "Visitors", "value": "50K/mo"}, {"label": "Donations", "value": "₹10L+"}, {"label": "Volunteers", "value": "500+"}], "external_image_url": "https://images.unsplash.com/photo-1544391874-ebddb26c9da5?w=800", "is_active": True},
    
    {"title": "NN Engineers Corporate Website", "slug": "nn-engineers-website", "category": "devops", "status": "completed", "shortDescription": "React-based corporate site showcasing engineering services, projects, and certifications", "description": "Professional corporate website for engineering consultancy showcasing services, completed projects, team profiles, and client testimonials.", "client": "NN Engineers Pvt Ltd", "team": "1 UI/UX engineer", "timeline": "3 months", "technologies": ["React", "JavaScript (ESNext)", "Custom CSS", "Webpack", "GitHub Pages", "Google Analytics"], "bullets": ["Responsive service catalog", "Project portfolio showcase", "Team profiles", "Client testimonials", "Contact form with email automation", "SEO optimization"], "challenges": ["Complex project showcase requirements", "Performance optimization", "SEO for engineering terms", "Legacy content migration"], "outcomes": ["300% increase in inquiries", "Top 3 Google ranking for key terms", "90+ PageSpeed score", "10K+ monthly visitors"], "stats": [{"label": "Inquiries", "value": "+300%"}, {"label": "PageSpeed", "value": "90+"}, {"label": "Visitors", "value": "10K/mo"}], "external_image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800", "is_active": True},
    
    {"title": "Odia OCR - Voter ID Data Extraction System", "slug": "odia-ocr-system", "category": "govtech", "status": "completed", "shortDescription": "Python-based OCR pipeline to extract voter details from 147 constituency PDFs into structured Excel format", "description": "Automated OCR system for extracting voter information from Odia language PDFs. Processes 147 constituency files and exports structured data to Excel.", "client": "Political Campaign", "team": "2 Python Developers", "timeline": "20 Days", "technologies": ["Python", "OCR Technology", "Pandas", "Tesseract", "OpenCV", "NumPy"], "bullets": ["Odia language OCR", "Batch PDF processing", "Data validation and cleaning", "Excel export with formatting", "Error logging and retry", "Progress tracking"], "challenges": ["Odia script recognition accuracy", "Handling poor quality scans", "Processing large PDF files", "Data validation"], "outcomes": ["147 constituencies processed", "2M+ voter records extracted", "95% accuracy achieved", "Completed in 15 days"], "stats": [{"label": "Constituencies", "value": "147"}, {"label": "Records", "value": "2M+"}, {"label": "Accuracy", "value": "95%"}], "external_image_url": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800", "is_active": True},
    
    {"title": "Train Simulator POC", "slug": "train-simulator-poc", "category": "govtech", "status": "completed", "shortDescription": "Indian Railway Simulator with interactive cockpit and realistic physics", "description": "Proof-of-concept train simulator for Indian Railways featuring realistic physics, interactive controls, multiple train models, and route scenarios.", "client": "Indian Railways", "team": "3D Artists + Developers", "timeline": "2 months", "technologies": ["Unity HDRP/URP", "Blender/Maya", "Substance Painter", "C#", "Physics Engines", "VR Support"], "bullets": ["Realistic train physics", "Interactive cockpit controls", "Multiple Indian train models", "Route scenarios across India", "VR headset support", "Weather and day-night cycle"], "challenges": ["Realistic physics simulation", "High-quality 3D models", "Performance optimization", "VR motion sickness mitigation"], "outcomes": ["5 train models completed", "3 route scenarios", "VR demo presented to Railways", "Approved for Phase 2 development"], "stats": [{"label": "Train Models", "value": "5"}, {"label": "Routes", "value": "3"}, {"label": "VR Support", "value": "Yes"}], "external_image_url": "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800", "is_active": True},
    
    {"title": "Dasho Exams – Digital Assessment Cloud", "slug": "dasho-exams", "category": "edtech", "status": "completed", "shortDescription": "Secure Online Exam Platform", "description": "Comprehensive online examination platform with question bank management, automated grading, proctoring, and analytics for educational institutions.", "client": "Educational Institutions", "team": "2 Developers", "timeline": "3 months", "technologies": ["React", "Django API", "PostgreSQL", "WebRTC", "Redis", "Docker"], "bullets": ["Question bank management", "Automated grading", "Browser lockdown", "AI-based proctoring", "Detailed analytics", "Certificate generation"], "challenges": ["Preventing cheating", "Handling concurrent exams", "Network reliability", "Fair proctoring"], "outcomes": ["100+ institutions using", "500K+ exams conducted", "99.5% uptime achieved", "90% reduction in exam costs"], "stats": [{"label": "Institutions", "value": "100+"}, {"label": "Exams", "value": "500K+"}, {"label": "Uptime", "value": "99.5%"}], "external_image_url": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800", "is_active": True}
]

print("\n" + "="*70)
print("FINAL BATCH: SEEDING LAST 8 PROJECTS")
print("="*70 + "\n")

for p in FINAL_BATCH:
    project, created = Project.objects.update_or_create(slug=p['slug'], defaults={k:v for k,v in p.items() if k!='slug'})
    print(f"✅ {p['title']}")

print("\n" + "="*70)
print(f"🎉 ALL {Project.objects.count()} PROJECTS SEEDED WITH COMPLETE DETAILS!")
print("="*70)
