# Generated by Django 3.2.7 on 2024-10-24 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(default='', max_length=250)),
                ('noticeText', models.TextField(blank=True, null=True)),
                ('creationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('globalNoticeID', models.CharField(max_length=15)),
                ('noticefile', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ('-creationTime',),
            },
        ),
    ]
