# Generated by Django 3.2.7 on 2023-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('photoFile', models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/')),
                ('signatureFile', models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/')),
                ('mobileno', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
