# Generated by Django 3.2.7 on 2023-09-02 16:49

from django.db import migrations, models
import onlineregistration.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='photoFile',
            field=models.ImageField(blank=True, default=onlineregistration.models.get_default_profile_image, max_length=5000, null=True, upload_to='images/'),
        ),
    ]
