# Generated by Django 3.2.7 on 2025-05-10 08:07

import Vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('houseno', models.CharField(blank=True, max_length=1000, null=True)),
                ('building_name', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('Villa', 'Villa')], default='Main Building', max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=1000, null=True)),
                ('vehicle_image', models.ImageField(blank=True, default=Vehicles.models.get_default_profile_image, max_length=255, null=True, upload_to='images/')),
                ('vehicle_type', models.CharField(blank=True, choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=10, null=True)),
                ('house_owner_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('owner_mobile_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('tenant_mobile_number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
